### ISSUE TITLE
Calibre 2.24, iOS reader application 1.4.7.0.0, Marvin, iPad 3 and nothing happens...

### ISSUE THREAD

**Issue by ksteiner** [Philantrop/calibre-ios-reader-applications#173]
Hi there,

I have a problem now with getting my iPad 3 working on version 8.13. My computer is a Mac operating with OSX, 10.10.2. I have Marvin installed on the iPad and Caliber 2.24.

I just updated to the most recent iOS reader application, 1.4.7.0.0 and since then I cannot find the Marvin button in calibre anymore. 

When I try to connect with my iPad, plugging in by USB and pressing connect, nothing happens in calibre.

I tried to have a look at customising the plug, I get the following error message

Import Error: cannot import name ConfigWidget.

If I ask for the details, the following information shows up

calibre, version 2.24.0
ERROR: Unhandled exception: <b>ImportError</b>:cannot import name ConfigWidget

calibre 2.24  isfrozen: True is64bit: True
Darwin-14.1.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '14.1.0', 'Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64')
Python 2.7.9
OSX: ('10.10.2', ('', '', ''), 'x86_64')
Successfully initialized third party plugins: DeDRM && K4PC, K4Mac, Kindle Mobi and Topaz DeDRM && Inept Epub DeDRM && Ignoble Epub DeDRM && eReader PDB 2 PML && Marvin XD && EpubSplit && iOS reader applications && Inept PDF DeDRM
Traceback (most recent call last):
  File "site-packages/calibre/gui2/preferences/plugins.py", line 289, in double_clicked
  File "site-packages/calibre/gui2/preferences/plugins.py", line 370, in modify_plugin
  File "site-packages/calibre/customize/__init__.py", line 154, in do_user_config
  File "calibre_plugins.ios_reader_apps.__init__", line 493, in config_widget
ImportError: cannot import name ConfigWidget

Any help would be highly appreciated....
